name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Build
      run: dotnet build ./WorkflowTest.Adder.UnitTests/WorkflowTest.Adder.UnitTests.csproj

    - name: Test
      run: dotnet test ./WorkflowTest.Adder.UnitTests/WorkflowTest.Adder.UnitTests.csproj --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./WorkflowTest.Adder.UnitTests/TestResults/Coverage/

    - name: Generate Coverage Report
      uses: danielpalme/ReportGenerator-GitHub-Action@5.0.0
      with:
        reports: './WorkflowTest.Adder.UnitTests/TestResults/Coverage/coverage.cobertura.xml'
        targetdir: 'coveragereport'
        reporttypes: 'HtmlInline;Cobertura;MarkdownSummary'

    - name: Publish coverage summary
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        path: coveragereport/Summary.md
