name: .NET

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build ./WorkflowTest.Adder.UnitTests/WorkflowTest.Adder.UnitTests.csproj
    - name: Test
      run: dotnet test ./WorkflowTest.Adder.UnitTests/WorkflowTest.Adder.UnitTests.csproj --no-build
