name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    types: [labeled, opened, reopened, synchronized]
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build ./WorkflowTest.Adder.UnitTests/WorkflowTest.Adder.UnitTests.csprojj
    - name: Test
      run: dotnet test ./WorkflowTest.Adder.UnitTests/WorkflowTest.Adder.UnitTests.csproj --no-build
